from .main_window import MainWindow
from .dialog_ui_settings import DialogUiSettings
from .widget_control_panel import ControlPanelWidget
from .dialog_channel_choose import DialogChannelChoose
from .dialog_device_info import DialogDeviceInfo
from .widget_spectrogram import SpectrogramWidget
from .widget_band_power import BandPowerWidget
from .widget_head_plot import HeadPlotWidget
from .dialog_settings_data_chain import DialogSettingsDataChain
